description:
  - "Discover my projects where I demonstrate creativity and problem-solving skills."

projects:
  - name: "Limit Order Book(C++) | High Performance Trading Engine"
    description: "Engineered a low-latency matching engine in C++"
    additional_description: "Utilized std::map and std::unordered_map to enforce price-time priority execution for Limit and Market orders, 
                            and Optimized memory management by implementing smart pointers and minimizing object copies, eliminating memory 
                            leaks and reducing overhead during high-frequency updates."
    date: "Dec 2025"
    svgIcons:
      - gatsby
      - aws
      - terraform
      - tailwind
    actions:
      - text: Repo
        link: https://github.com/algebananazzzzz/NocturnalProject
      - text: Demo
        color: purple
        video: demo.mp4

  - name: "Project 2"
    description: "A succinct description of the project's purpose and functionality"
    additional_description: "A detailed description on the project's architecture, key components, and any unique selling points."
    date: "Apr 2024"
    svgIcons:
      - gatsby
      - aws
      - terraform
      - tailwind
    actions:
      - text: Repo
        link: https://github.com/algebananazzzzz/NocturnalProject
      - text: Demo
        color: purple
        video: demo.mp4

  - name: "Project 3"
    description: "A succinct description of the project's purpose and functionality"
    additional_description: "A detailed description on the project's architecture, key components, and any unique selling points."
    date: "Apr 2024"
    svgIcons:
      - gatsby
      - aws
      - terraform
      - tailwind
    actions:
      - text: Repo
        link: https://github.com/algebananazzzzz/NocturnalProject
      - text: Demo
        color: purple
        video: demo.mp4
        