description:
  - "Discover my projects where I demonstrate creativity and problem-solving skills."

projects:
  - name: "Limit Order Book(C++) | High Performance Trading Engine"
    description: "Engineered a low-latency matching engine in C++"
    additional_description: "Utilized std::map and std::unordered_map to enforce price-time priority execution for Limit and Market orders, 
                            and Optimized memory management by implementing smart pointers and minimizing object copies, eliminating memory 
                            leaks and reducing overhead during high-frequency updates."
    date: "Dec 2025"
    svgIcons:
      - python
      - cpp
    actions:
      - text: Repo
        link: https://github.com/stinkray77/Cpp-Limit-Order-Book
      - text: Demo
        color: purple
        video: demo.mp4

  - name: "Gradwise"
    description: "Academic Web Planning App | NUS Orbital 2025"
    additional_description: "Designed and deployed a React + Node.js + MongoDB 
                            platform enabling students to optimize academic planning"
    date: "May 2025"
    svgIcons:
      - python
      - reactjs
      - tailwind
      - css
      - html
      - typescript
    actions:
      - text: Repo
        link: https://github.com/lanjia0/orbital
      - text: Demo
        color: purple
        video: demo.mp4

  - name: "LocationTrust"
    description: "ML Review Validation Tool, Developed an ML-powered system to detect 
                  policy violations and evaluate trustworthiness of Google reviews"
    additional_description: "Trained and deployed NLP classification models, 
                            achieving 85.5% accuracy in review authenticity detection."
    date: "Aug 2025"
    svgIcons:
      - python
    actions:
      - text: Repo
        link: https://github.com/2AcademicVictims/LocationTrust
      - text: Demo
        color: purple
        video: demo.mp4
        